repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: gunicorn_config.py
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: (migrations)
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat
          - flake8-bugbear
        args: [--max-line-length=90, --ignore=B008, --ignore=F405]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: poetry-export
        name: poetry export requirements.txt
        entry: poetry export --without-hashes --format requirements.txt --output requirements.txt --without-hashes
        language: system
        pass_filenames: false
        stages: [ commit ]
        verbose: true
