# Generated by Django 5.1.1 on 2024-09-22 08:37
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
    ]
